---
title: "Code Portfolio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### R Customization

[Rprofile.site](https://github.com/dgabbe/rprofile.site#rprofilesite)
  ~ `Rprofile.site` and `.Renviron` to set some reasonable defaults.  Complete
  installation instructions are provided along with install and uninstall scripts.
  
[wdprompt](http://blog.frame38.com/wdprompt/reference/wdprompt-package.html)
  ~ A package to change R's console prompt to display the current working directory
  similar to the bash prompt.  Implemented as a taskCallback to make it independent 
  of clearing the environment.
  
### R Utilities

[dgutils](http://blog.frame38.com/dgutils/reference/dgutils-package.html)
  ~ A package consisting of aliases, functions, and graphical themes that improve
  one's efficiency and workflow.

### Shiny Apps

[Tire Pressure](https://dgabbe.shinyapps.io/tire_pressure_shiny)
  ~ This app calculates optimal bicycle tire inflation pressures.  If you race or 
  ride long distance events, this simple change could make the difference between a podium spot 
  or missing the time cutoff.  
  
  This version is a proof on concept focusing on reusing the 
  analysis functions unchanged in the Shiny app and displaying the tire widths by their
  inflations curves with [directlabels]( http://directlabels.r-forge.r-project.org/).
